### ISSUE TITLE
InstantSend failing with ChangeAddressMissing when using FEE_PER_KB = 1000

### ISSUE THREAD

**Issue by BenjaminNitschke** [dashpay/dashcore-lib#109]
The defaults in dashcore-lib are 10x too high:
Transaction.FEE_PER_KB = 10000;

Normal Dash transactions work fine with 1 duff per byte, thus we use:
Transaction.FEE_PER_KB = 1000;

However, when using InstantSend the security margins don't work and are not even checked in Transaction.prototype._estimateFee, which is by default:
Transaction.FEE_SECURITY_MARGIN = 15;

Increasing this to 100 works, or simply disabling the whole check in Transaction.prototype._hasFeeError via opts.disableLargeFees is a workaround. Would be better if InstantSend is actually integrated and checked when building transactions FEE_PER_KB is not relevant, it must be 10000 duffs=0.1mDASH per input, FEE_SECURITY_MARGIN of 15 or higher is also not very useful for DASH imo, 2 would be more than enough as all tx fit fine with the minimum fee.

Another simple fix would be to just use the same check for InstantSend as is used isSpecialTransaction to skip the whole utxo checking.

For https://MyDashWallet.org we have decided to disable the whole check as too many users had problems in the past with complex inputs (>5, small amounts each). Example:
7 inputs: 0.00001+0.00009626+0.0001+0.0001+0.0001+0.0001+0.00319286 = 0.00369912 DASH = 369912 duffs
outputs: 170000 + 129912
fee: 70000 (7*0.1mDASH)
sum: 170000 + 129912 + 70000 = 369912 duffs

**Comment by antouhou** [comment]
Hey @BenjaminNitschke ! 
The default fee is too big, yes, thank you for pointing that out.

However I'm not sure I got the rest.

What is the exact issue?

`Transaction.prototype._estimateFee` estimates fee. It shouldn't check security margin. Security margin is checked during transaction serialization. If the amount in the transaction that won't be redeemed is 15 times bigger than the estimated fee than this check fails. This is the same process for normal transactions and InstantSend transactions.

So, if you want to set up fee on a level of 1 duff per byte, this means that this check will fail if the actual fee will be around 15 duffs per byte.

`isSpecialTranansaction` doesn't skip the utxo checking. Utxo checking is omitted in case if the transaction is a particular transaction of one particular type that _can't have any inputs or outputs_. InstaSend can, and even must have them, so skipping this check isn't an option.

**Comment by BenjaminNitschke** [comment]
The issue pops up because when setting Transaction.FEE_PER_KB = 1000 the FEE_SECURITY_MARGIN of 15 is not enough to cover InstantSend transactions (which have a fee of 100000 duffs, 100 times more than the fee per kb, not just 15 times more). There is no code at all to handle InstantSend tx fees in _hasFeeError as far as I can see and isSpecialTranansaction seems to skip it based on the sign function.

**Comment by antouhou** [comment]
@BenjaminNitschke There is no code that checks if a transaction is InstantSend because InstantSend transaction is just a regular transaction until it was broadcasted to the network and the lock was applied. It's impossible to tell if a transaction is InstantSend or not until you've sent it to the network. I guess that just rising security margin should solve the problem

`isSpecialTransaction` returns a boolean based on the transaction type and version:
https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/transaction.js#L1317

Fee check is omitted in `serialize` method only for the very specific transaction type - StateTransition - that _can't have a fee_, not just for any special transaction. InstantSend, on the other hand, must have a fee.

I'll prepare a solution and get back to you, will leave the issue open until then.

Thank you for the report! :)

**Comment by antouhou** [comment]
Hey @BenjaminNitschke 

I've fixed that issue with InstandSend. You can check it out here: https://github.com/dashevo/dashcore-lib/pull/111

I've used a different approach and added proper fee estimation for InstantSend to fee check.

**Comment by nmarley** [comment]
Fixed in #111, closing.
